### PR TITLE
Date picker component: Initial design

### PR DESCRIPTION
**Pull request by aquibbaig**
Will be tracking up the progress of date-picker-component in this PR:

### CODE REVIEW

**Comment by aquibbaig** [comment]
Screenshot 2020-05-26 at 8 28 34 PM

**Comment by gurbirkalsi** [comment]
@aquibbaig It seems the `react-date-range` component takes up a lot of space on the page - especially when wrapped in a modal. What if we considered utilizing the Date Picker component offered by Ant Design? https://ant.design/components/date-picker/#components-date-picker-demo-presetted-ranges

There's also support for overriding default component CSS: https://pro.ant.design/docs/style#override-the-component-style

**Comment by aquibbaig** [comment]
> @aquibbaig It seems the `react-date-range` component takes up a lot of space on the page - especially when wrapped in a modal. What if we considered utilizing the Date Picker component offered by Ant Design? https://ant.design/components/date-picker/#components-date-picker-demo-presetted-ranges
> 
> There's also support for overriding default component CSS: https://pro.ant.design/docs/style#override-the-component-style

@gurbirkalsi, agreed! That way I guess the modal isn't necessary anymore.

**Comment by aquibbaig** [comment]
Date picker component

@gurbirkalsi How does it look?

**Comment by gurbirkalsi** [comment]
Looks great!

**Pull request closed without merging**
