### PR TITLE
Check the dispatch function

### PR DESCRIPTION
**Pull request by anishaswain**

### CODE REVIEW

**Comment by anishaswain** [comment]
@gurbirkalsi the issue is the `getMoreToCresult` function is not being able to call `fetchTocResult` function.

**Comment by gurbirkalsi** [comment]
Do you have stack trace or console error output when calling this function? Some additional context here would be helpful for debugging this issue, thanks!

**Comment by aquibbaig** [comment]
@Anisha1234 I debugged the `dispatch` function by pulling your branch and `console.log('called')` works for me.

**Comment by anishaswain** [comment]
@aquibbaig then something is wrong with my system setup I believe. Thanks for the update. I will remove all the changes and redo it again and will let you know if it works.

**Comment by anishaswain** [comment]
Resolved. Closing the PR for the same.

**Pull request closed without merging**
