### PR TITLE
Pbench Documentation Site Design

### PR DESCRIPTION
**Pull request by anishaswain**
The site is designed using PatternFly 4 with some slight CSS modifications. 
[Pbench website development guide
](https://docs.google.com/document/d/1xAlOZyzFU0xH_4v3QdLxCIiWnUp-79-2i9FEMJo4Rvc/edit?usp=sharing)

Wire Frame: 
[pbench-wires.pdf](https://github.com/distributed-system-analysis/pbench-dashboard/files/4354348/pbench-wires.pdf)

_Will update page screenshots  soon_

### CODE REVIEW

**Review by gurbirkalsi — CHANGES_REQUESTED** [review]
@Anisha1234 Our code should be structured as a typical website, e.g. with the primary entry point being an HTML file called `index.html`.

**Comment by anishaswain** [comment]
> @Anisha1234 Our code should be structured as a typical website, e.g. with the primary entry point being an HTML file called `index.html`.

Fixed

**Comment by anishaswain** [comment]
@maryshak1996 the implementation of Pbench documentation page is being tracked in this PR.

**Comment by portante** [comment]
Shouldn't this be done in the pbench repo?  Since the contents of this document is going to be for the agent and server?

**Comment by gurbirkalsi** [comment]
Closing in favor of re-opening this PR @distributed-system-analysis/pbench

**Pull request closed without merging**
