### PR TITLE
reference url in the prisma data model

### PR DESCRIPTION
**Pull request by aquibbaig**
Url was not referenced in the prisma data model due to which we were not able to add new urls of the sessions created in the `Explore` page. This PR is aimed at fixing #88 and #83

### CODE REVIEW

**Comment by aquibbaig** [comment]
I changed to endpoint to `localhost` for this result. We might need to re-deploy the prisma instance for the dashboard to work correctly.

Screenshot 2020-09-21 at 2 45 43 PM

**Comment by gurbirkalsi** [comment]
Looks good @aquibbaig, can you verify these changes by redeploying the Prisma instance on staging? Please let me know if you need help doing that.

**Comment by aquibbaig** [comment]
@gurbirkalsi This is clean and mergable! Tested it out thoroughly.

**Comment by gurbirkalsi** [comment]
Great work @aquibbaig!

**Pull request merged**
