### PR TITLE
Use real /datasets/list and /datasets/detail APIs

### PR DESCRIPTION
**Pull request by dbutenhof**
Switch over the dashboard service and model effects to use the Pbench server /datasets/list and /datasets/detail APIs.

This also fixes an issue in the use of the Elasticsearch pass-through API for TOC.

### CODE REVIEW

**Review by portante — APPROVED** [review]

**Review by portante — CHANGES_REQUESTED** [review]
On the surface they look good, but the unit tests don't seem to like them.

**Comment by dbutenhof** [comment]
> On the surface they look good, but the unit tests don't seem to like them.

Now how could my changes have affected the attempt to reverse the order of controllers on the controllers page? That's disturbing. I guess I'll need to figure out how to debug this...

**Comment by aquibbaig** [comment]
@dbutenhof Restarting the job!

**Comment by dbutenhof** [comment]
> @dbutenhof Restarting the job!

Well that's interesting; apparently it was a fluke. I've had so much trouble with the dashboard e2e tests locally that it didn't even occur to me that it wasn't somehow my fault! ;-)

**Review by aquibbaig — APPROVED** [review]
Looks good, Dave!

**Comment by dbutenhof** [comment]
> Looks good, Dave!

Thanks. GitHub is being weird again; even weirder than usual. It shows that you approved in the conversation history, but there's no checkmark. And when I requested a re-review from Pete after your retriggered tests ran, it says I also requested review from you. Sigh. After our Pbench-side experimentations I'm not entirely convinced that GerritHub is a viable replacement, but GitHub's review experience seems to be getting progressively worse rather than better ...

**Comment by aquibbaig** [comment]
> > Looks good, Dave!
> 
> Thanks. GitHub is being weird again; even weirder than usual. It shows that you approved in the conversation history, but there's no checkmark. And when I requested a re-review from Pete after your retriggered tests ran, it says I also requested review from you. Sigh. After our Pbench-side experimentations I'm not entirely convinced that GerritHub is a viable replacement, but GitHub's review experience seems to be getting progressively worse rather than better ...

Strange!

**Review by portante — APPROVED** [review]

**Review by gurbirkalsi — APPROVED** [review]

**Pull request merged**
